config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
    get "pages/index"
    get "pages/vitality"
    get "cities/my_cities"
  
  devise_for :users
  
  resources :salons do 
    resources :notes
    resources :tasks
  end

  resources :cities do 
  	resources :zip_codes do 
  		resources :salons
  	end
  end

  resources :sales_sessions do 
    resources :sales_actions
  end

  resources :form_contacts
end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :zip_codes
	belongs_to :user
end

app/models/form_contact.rb
class FormContact < ActiveRecord::Base
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :salon
  belongs_to :user
end

app/models/sales_action.rb
class SalesAction < ActiveRecord::Base
  belongs_to :user
  belongs_to :salon
  belongs_to :sales_session
end

app/models/sales_session.rb
class SalesSession < ActiveRecord::Base
	belongs_to :user
	has_many :sales_actions
end

app/models/salon.rb
class Salon < ActiveRecord::Base
	belongs_to :zip_code
	belongs_to :user
	has_many :notes	
	has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
	belongs_to :salon
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :cities
  has_many :salons
  has_many :notes
  has_many :tasks
  has_many :sales_sessions
  has_many :sales_actions
end

app/models/zip_code.rb
class ZipCode < ActiveRecord::Base
	belongs_to :city
	belongs_to :user
	has_many :salons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def require_admin
  	unless current_user.admin?
  		redirect_to root_url, notice: "Unauthorized Access!"
  	end
  end
end

app/controllers/form_contacts_controller.rb
class FormContactsController < ApplicationController
  before_action :set_form_contact, only: [:show, :edit, :update, :destroy]
  invisible_captcha only: [:create, :update], honeypot: :physical_address

  # GET /form_contacts
  # GET /form_contacts.json
  def index
    @form_contacts = FormContact.all
  end

  # GET /form_contacts/1
  # GET /form_contacts/1.json
  def show
  end

  # GET /form_contacts/new
  def new
    @form_contact = FormContact.new
  end

  # GET /form_contacts/1/edit
  def edit
  end

  # POST /form_contacts
  # POST /form_contacts.json
  def create
    @form_contact = FormContact.new(form_contact_params)

    respond_to do |format|
      if @form_contact.save
        AdminMailer.message_alert(@form_contact).deliver
        format.html { redirect_to root_path, notice: 'Thank You!  We will follow up shortly.' }
        format.json { render :show, status: :created, location: @form_contact }
      else
        format.html { render :new }
        format.json { render json: @form_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_contacts/1
  # PATCH/PUT /form_contacts/1.json
  def update
    respond_to do |format|
      if @form_contact.update(form_contact_params)
        format.html { redirect_to @form_contact, notice: 'Form contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @form_contact }
      else
        format.html { render :edit }
        format.json { render json: @form_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_contacts/1
  # DELETE /form_contacts/1.json
  def destroy
    @form_contact.destroy
    respond_to do |format|
      format.html { redirect_to form_contacts_url, notice: 'Form contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form_contact
      @form_contact = FormContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_contact_params
      params.require(:form_contact).permit(:name, :email, :phone, :zip_code, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@form_contact = FormContact.new
	end

	def vitality
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/salons_helper.rb
module SalonsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/zip_codes_helper.rb
module ZipCodesHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :city_name %><br>
    <%= f.text_field :city_name %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :population %><br>
    <%= f.text_field :population %>
  </div>
  <div class="field">
    <%= f.label :wiki_link %><br>
    <%= f.text_field :wiki_link %>
  </div>
  <div class="field">
    <%= f.label :wiki_text %><br>
    <%= f.text_area :wiki_text %>
  </div>
  <div class="field">
    <%= f.label :city_url %><br>
    <%= f.text_field :city_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cities</h1>

<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>ID</th>
      <th>City name</th>
      <th>State</th>
      <th>Population</th>
      <th>Wiki link</th>
      <th>Wiki text</th>
      <th>City url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.id %></td>
        <td><%= city.city_name %></td>
        <td><%= city.state %></td>
        <td><%= city.population %></td>
        <td><%= city.wiki_link %></td>
        <td><%= city.wiki_text.truncate(140) %></td>
        <td><%= city.city_url %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Add Zip', new_city_zip_code_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/my_cities.html.erb
<% @cities.each do |city| %>
<h3><%= city.city_name %>, <%= city.state %> | Population: <%= city.population %></h3>
<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>Business name</th>
      <th>TZ</th>
      <th>Email</th>
      <th>Contact</th>
      <th>Website?</th>
      <th>Web Address</th>
      <th>Appt?</th>
      <th>Mobile?</th>
      <th>Phone</th>
      <th>Stage</th>
      <th>Zip code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<% @zips = ZipCode.where(city_id: city.id) %>
  	<% @salons = [] %>
  	<% @zips.each do |zip| %>
  	<% @salons = Salon.where(zip_code_id: zip.id) %>
    <% @salons.each do |salon| %>
      <tr>
        <td><%= salon.business_name %></td>
        <td><%= salon.time_zone %></td>
        <td><%= salon.email %></td>
        <td><%= salon.contact %></td>
        <td><%= salon.website %></td>
        <td><%= salon.web_address %></td>
        <td><%= salon.appointment_scheduling %></td>
        <td><%= salon.mobile_ready %></td>
        <td><%= salon.phone %></td>
        <td><%= salon.stage %></td>
        <td><%= salon.zip_code_id %></td>
        <td><%= link_to 'Show', city_zip_code_salon_path(city, zip, salon) %></td>
        <td><%= link_to 'Edit', edit_city_zip_code_salon_path(city, zip, salon) %></td>
        <td><%= link_to 'Destroy', [city, zip, salon], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
	
<% end %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wiki link:</strong>
  <%= @city.wiki_link %>
</p>

<p>
  <strong>Wiki text:</strong>
  <%= @city.wiki_text %>
</p>

<p>
  <strong>City name:</strong>
  <%= @city.city_name %>
</p>

<p>
  <strong>State:</strong>
  <%= @city.state %>
</p>

<p>
  <strong>Population:</strong>
  <%= @city.population %>
</p>

<p>
  <strong>City url:</strong>
  <%= @city.city_url %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %> |
<%= link_to 'Add Zip', new_city_zip_code_path(@city) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">

	<title>Burke Remodeling</title>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

	<!-- Default Fonts (IMPORTANT: Delete these if you are using a different body style!) -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,600,500,700,800,900' rel='stylesheet' type='text/css'>

    <!-- Modern Style Fonts (IMPORTANT: Delete these unless you are using body.modern!) -->
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cardo:400,400italic,700' rel='stylesheet' type='text/css'>

    <!-- Vintage Style Fonts (IMPORTANT: Delete these unless you are using body.vintage!) -->
    <link href='https://fonts.googleapis.com/css?family=Sanchez:400italic,400' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cardo:400,400italic,700' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sales_actions/new.html.erb
<p>Your First Stop Is: <b><%= @salon.business_name %></b></p>
<p>Go To: <b><%= "#{@salon.street_address}, #{@salon.zip_code.city.city_name}, #{@salon.zip_code.city.state} #{@salon.zip_code.zip}" %></b></p>

<h4>Contact Information:</h4>
<ul>
  <% if @salon.contact? %>
	<li>Contact Name: <%= @salon.contact %></li>
  <% end %>
  <% if @salon.phone? %>
	<li>Phone Number: <%= @salon.phone %></li>
  <% end %>
  <% if @salon.stage? %>
	<li>Current Stage: <%= @salon.stage %></li>
  <% end %>
  	<li>Do they have a website? <%= @salon.website %></li>
  <% if @salon.website? %>
	<li>Web Address: <%= @salon.web_address %></li>
  <% end %>	
  	<li>Is it Mobile Responsive? <%= @salon.mobile_ready %></li>
  	<li>Appointment Scheduling Online? <%= @salon.appointment_scheduling %></li>
</ul>
<p>Notes:</p>
<% @salon.notes.each do |note| %>
	<p><%= note.body %></p>
	<p>Created: <%= note.created_at.strftime("%a, %b %d, %Y") %></p>
	<p>---------------------</p>
<% end %>

app/views/sales_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 text-center">
      <h2>Ready to Sell?</h2>

      <h3>A Couple Questions:</h3>

      <%= form_for(@sales_session) do |f| %>
        <% if @sales_session.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@sales_session.errors.count, "error") %> prohibited this city from being saved:</h2>

            <ul>
            <% @sales_session.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <h3><span>How are you prospecting? <br /><%= f.select(:walking, options_for_select([['Walk Into Businesses', true], ['Calling on the Phone', false]]), class: "form-control ") 
          %></span></h3>

        <h3><span>Where are you now? <small><%= f.text_field :start_location, :placeholder => 'Address, City, State or Zip', :class => "form-control input-lg" %></small></span></h3>
        <div class="actions">
      	<%= f.submit "Next >>", :class => "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/salons/_form.html.erb
<%= form_for([@city, @zip_code, @salon]) do |f| %>
  <% if @salon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salon.errors.count, "error") %> prohibited this salon from being saved:</h2>

      <ul>
      <% @salon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :business_name %><br>
    <%= f.text_field :business_name %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br>
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :time_zone %><br>
    <%= f.select(:time_zone, options_for_select([['EDT', 'EDT'], ['CDT', 'CDT'], ['MDT', 'MDT'],['PST', 'PST']]), class: "form-control") 
    %>
  </div>
   <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :stage %><br>
    <%= f.select(:stage, options_for_select([['Prospect', 'prospect'], ['Contact', 'contact'], ['Call Back', 'call_back'], ['Demo', 'demo'], ['Closed YES', 'closed_yes'],['Closed NO', 'closed_no'], ['Bad Number', 'bad_number']]), class: "form-control") 
    %>
  </div>
  <div class="field">
    <%= f.label :web_address %><br>
    <%= f.text_field :web_address %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.check_box :website %>
  </div>
  <div class="field">
    <%= f.label :mobile_ready %><br>
    <%= f.check_box :mobile_ready %>
  </div>
  <div class="field">
    <%= f.label :appointment_scheduling %><br>
    <%= f.check_box :appointment_scheduling %>
  </div>
  <div class="field">
    <%= f.label :zip_code_id %><br>
    <%= f.number_field :zip_code_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salons/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h1>Editing Salon</h1>

			<%= render 'form' %>
		</div>

		<div class="col-md-6">
			<h4 class="notes_title text-center">Notes</h4>
		    <%= form_for [@salon, Note.new] do |f| %>
		    <div class="field">
		        <div class="input-group">
		        <%= f.text_field :body, class: "form-control body", :required => true, :placeholder => 'Add Note', :style => 'height: 36px !important;' %>
		        <div class="input-group-addon"><%= f.submit 'Create', class: 'nothing' %></div>
		        </div>
		    </div>
		    <% end %>
		    <div class="notes-margin">

		        <% @salon.notes.each do |note| %>
		        <p>Created At: <%= note.created_at %></p>
		        <p><%= note.body %></p>
		        <% end %>

		    </div><br />
			<h4 class="tasks_title text-center">Tasks</h4>
		    <%= form_for [@salon, Task.new] do |f| %>
		        <div class="input-group">
		        <%= f.text_field :title, class: "form-control body", :required => true, :placeholder => 'Task Title', :style => 'height: 36px !important;' %>
		        </div>
		        <div class="input-group">
		        <%= f.text_field :details, class: "form-control body", :required => true, :placeholder => 'Add Details', :style => 'height: 36px !important;' %>
		        </div>
		        <%= f.submit 'Create', class: 'btn btn-default' %>
		    <% end %>
		    <div class="notes-margin">

		        <% @salon.tasks.each do |task| %>
		        <p>Due At: <%= task.due_at %></p>
		        <p><%= task.title %></p>
		        <p><%= task.details %></p>
		        <p>----------------------</p>
		        <% end %>

		    </div>
		</div>
	</div>
	<%= link_to 'Show', city_zip_code_salon_path(@city, @zip_code, @salon), class: "btn btn-default" %> |
	<%= link_to 'Back', city_zip_code_salons_path(@city, @zip_code), class: "btn btn-default" %>
</div>

app/views/salons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Salons</h1>

<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>Business name</th>
      <th>Email</th>
      <th>Contact</th>
      <th>Website?</th>
      <th>Web Address</th>
      <th>Appt?</th>
      <th>Mobile?</th>
      <th>Phone</th>
      <th>Stage</th>
      <th>Zip code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salons.each do |salon| %>
      <tr>
        <td><%= salon.business_name %></td>
        <td><%= salon.email %></td>
        <td><%= salon.contact %></td>
        <td><%= salon.website %></td>
        <td><%= salon.web_address %></td>
        <td><%= salon.appointment_scheduling %></td>
        <td><%= salon.mobile_ready %></td>
        <td><%= salon.phone %></td>
        <td><%= salon.stage %></td>
        <td><%= salon.zip_code_id %></td>
        <td><%= link_to 'Show', city_zip_code_salon_path(@city, @zip_code, salon) %></td>
        <td><%= link_to 'Edit', edit_city_zip_code_salon_path(@city, @zip_code, salon) %></td>
        <td><%= link_to 'Destroy', [@city, @zip_code, salon], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salon', new_city_zip_code_salon_path(@city, @zip_code) %>

app/views/salons/new.html.erb
<div class="container">
<div class="row">
<div class="col-sm-12 center">
<h1>New Salon</h1>

<%= render 'form' %>

<%= link_to 'Back', city_zip_code_salons_path(@city, @zip_code) %>
</div>
</div>
</div>

app/views/salons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Business name:</strong>
  <%= @salon.business_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @salon.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @salon.phone %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @salon.stage %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @salon.zip_code_id %>
</p>

<%= link_to 'Edit', edit_city_zip_code_salon_path(@city, @zip_code, @salon) %> |
<% if current_user.admin? %>
<%= link_to 'Back', city_zip_code_salons_path(@city, @zip_code) %>
<% else %>
<%= link_to 'Back', cities_my_cities_path %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>
  <div class="field">
    <%= f.label :text_alert %><br>
    <%= f.check_box :text_alert %>
  </div>
  <div class="field">
    <%= f.label :due_at %><br>
    <%= f.datetime_select :due_at %>
  </div>
  <div class="field">
    <%= f.label :completed_at %><br>
    <%= f.datetime_select :completed_at %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Details</th>
      <th>Text alert</th>
      <th>Due at</th>
      <th>Completed at</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.details %></td>
        <td><%= task.text_alert %></td>
        <td><%= task.due_at %></td>
        <td><%= task.completed_at %></td>
        <td><%= task.completed %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Details:</strong>
  <%= @task.details %>
</p>

<p>
  <strong>Text alert:</strong>
  <%= @task.text_alert %>
</p>

<p>
  <strong>Due at:</strong>
  <%= @task.due_at %>
</p>

<p>
  <strong>Completed at:</strong>
  <%= @task.completed_at %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/zip_codes/_form.html.erb
<%= form_for([@city, @zip_code]) do |f| %>
  <% if @zip_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zip_code.errors.count, "error") %> prohibited this zip_code from being saved:</h2>

      <ul>
      <% @zip_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.number_field :city_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zip_codes/edit.html.erb
<h1>Editing Zip Code</h1>

<%= render 'form' %>

<%= link_to 'Show', city_zip_code_path(@city, @zip_code) %> |
<%= link_to 'Back', city_zip_codes_path(@city) %>

app/views/zip_codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Zip Codes</h1>

<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>Zip</th>
      <th>City</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @zip_codes.each do |zip_code| %>
      <tr>
        <td><%= zip_code.zip %></td>
        <td><%= @city.city_name %></td>
        <td><%= link_to 'Add Salon', new_city_zip_code_salon_path(@city, zip_code) %></td>
        <td><%= link_to 'View Salons', city_zip_code_salons_path(@city, zip_code) %></td>
        <td><%= link_to 'Show', city_zip_code_path(@city, zip_code) %></td>
        <td><%= link_to 'Edit', edit_city_zip_code_path(@city, zip_code) %></td>
        <td><%= link_to 'Destroy', [@city, zip_code], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zip code', new_city_zip_code_path(@city), class: "btn btn-default" %>

app/views/zip_codes/new.html.erb
<h1>New Zip Code</h1>

<%= render 'form' %>

<%= link_to 'Back', city_zip_codes_path(@city) %>

app/views/zip_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zip:</strong>
  <%= @zip_code.zip %>
</p>

<p>
  <strong>City:</strong>
  <%= @zip_code.city_id %>
</p>

<%= link_to 'Edit', edit_city_zip_code_path(@city, @zip_code) %> |
<%= link_to 'Add Salon', new_city_zip_code_salon_path(@city, @zip_code) %> |
<%= link_to 'Back', city_zip_codes_path(@city) %>